module.exports.config = {
  name: "gura2",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Teri",
  description: "Random ảnh gura",
  commandCategory: "hololive",
  usages: "gura2",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
    
};

module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
  var link = [
  "https://i.imgur.com/0cq1lkp.jpeg",
  "https://i.imgur.com/Wnr3OaT.jpeg",
  "https://i.imgur.com/0Kpd274.jpeg",
  "https://i.imgur.com/rLkYSz9.jpeg",
  "https://i.imgur.com/34OflmS.jpeg",
  "https://i.imgur.com/sWfjbH6.jpeg",
  "https://i.imgur.com/C8wKwEW.jpeg",
  "https://i.imgur.com/2NeoGnf.jpeg",
  "https://i.imgur.com/FT4l6w0.jpeg",
  "https://i.imgur.com/SQlBPW2.jpeg",
  "https://i.imgur.com/NivyPnj.jpeg",
  "https://i.imgur.com/v7IqcOL.png",
  "https://i.imgur.com/eTyi7If.jpeg",
  "https://i.imgur.com/39N1mQh.jpeg",
  "https://i.imgur.com/enej4CV.jpeg",
  "https://i.imgur.com/BwstKyK.jpeg",
  "https://i.imgur.com/pkhDb2W.jpeg",
  "https://i.imgur.com/JEonwU1.jpeg",
  "https://i.imgur.com/lmaY68X.jpeg",
  "https://i.imgur.com/OHQFOo4.jpeg",
  "https://i.imgur.com/1RZo8GK.jpeg",
  "https://i.imgur.com/mSLR9j9.jpeg",
  "https://i.imgur.com/wvQ5uiy.jpeg",
  "https://i.imgur.com/me7MU7B.jpeg",
  "https://i.imgur.com/hyaGrhc.jpeg",
  "https://i.imgur.com/ZhyXix8.jpeg",
  "https://i.imgur.com/TJWxMGf.jpeg",
  "https://i.imgur.com/xNd8ki6.png",
  "https://i.imgur.com/kMaJjOD.png",
  "https://i.imgur.com/drKLwrf.jpeg",
  "https://i.imgur.com/w2ZccCW.png",
  "https://i.imgur.com/zZLbdPc.jpeg",
  "https://i.imgur.com/OoGuNYa.jpeg",
  "https://i.imgur.com/C1aBYll.jpeg",
  "https://i.imgur.com/wmYbI2V.jpeg",
  "https://i.imgur.com/4WptECl.jpeg",
  "https://i.imgur.com/YdmQ6b0.jpeg",
  "https://i.imgur.com/eP3t1hr.png",
  "https://i.imgur.com/MTRC8Yr.jpeg",
  "https://i.imgur.com/kJSaIe9.jpeg",
  "https://i.imgur.com/nAezjDK.jpeg",
  "https://i.imgur.com/auspoKR.png",
  "https://i.imgur.com/x5h7VVx.jpg",
  "https://i.imgur.com/PV34Q6a.jpeg",
  "https://i.imgur.com/cNXafmR.jpeg",
  "https://i.imgur.com/ucIQeMh.jpeg",
  "https://i.imgur.com/5UhHxrD.jpeg",
  "https://i.imgur.com/bqgvWvZ.jpeg",
  "https://i.imgur.com/AavvM9I.png",
  "https://i.imgur.com/uqSRJpx.png",
  "https://i.imgur.com/fpqtyH2.jpeg",
  "https://i.imgur.com/XYjj6Q1.jpeg",
  "https://i.imgur.com/qxyVkac.jpeg",
  "https://i.imgur.com/6tVR5cK.jpeg",
  "https://i.imgur.com/nNwErOA.jpeg",
  "https://i.imgur.com/Kjs3xhe.jpeg",
  "https://i.imgur.com/hJw6IOI.png",
  "https://i.imgur.com/39N1mQh.jpeg",
  "https://i.imgur.com/BwstKyK.jpeg",
  "https://i.imgur.com/djF4GjJ.jpeg",
  "https://i.imgur.com/NhPKZCk.jpeg",
  "https://i.imgur.com/STSSfWA.jpeg",
  "https://i.imgur.com/1rNOF5N.jpeg",
  "https://i.imgur.com/Y8cspl9.jpeg",
  "https://i.imgur.com/C92aHhf.jpeg",
  "https://i.imgur.com/ajNrqvJ.jpeg",
  "https://i.imgur.com/djtSs4b.jpeg",
  "https://i.imgur.com/uy37tn9.jpeg",
  "https://i.imgur.com/jJIxHoA.jpeg",
  "https://i.imgur.com/6ybuSfw.jpeg",
  "https://i.imgur.com/1THvrtO.jpeg",
  "https://i.imgur.com/koj9oE8.jpeg",
  "https://i.imgur.com/1yCwJep.jpeg",
  "https://i.imgur.com/U7itZcD.jpeg",
  "https://i.imgur.com/5Q2oUMg.jpeg",
  "https://i.imgur.com/GWUkfNe.jpeg",
  "https://i.imgur.com/yvHwReF.jpeg",
  "https://i.imgur.com/EK5BsKH.jpeg",
  "https://i.imgur.com/cX0h5jI.jpeg",
  "https://i.imgur.com/j0dwzN3.jpeg",
  "https://i.imgur.com/LxYalUv.png",
  "https://i.imgur.com/ZHJTrvN.jpg",
  "https://i.imgur.com/Q2H5nlP.jpg",
"https://i.imgur.com/povbTsR.jpg",
"https://i.imgur.com/8sfKdmJ.jpg",
"https://i.imgur.com/yxe5CqS.jpg",
"https://i.imgur.com/svgQZOG.jpg",
"https://i.imgur.com/7FzY58H.jpg",
"https://i.imgur.com/GBK3SEs.jpg",
"https://i.imgur.com/7SRmqGP.jpg",
"https://i.imgur.com/LwHh3so.jpg",
"https://i.imgur.com/LQflm38.png",
"https://i.imgur.com/OEzBrR8.png",
"https://i.imgur.com/K5OqnYg.png",
"https://i.imgur.com/fnimyTy.jpg",
"https://i.imgur.com/3zK0Kzu.png",
"https://i.imgur.com/iMEv4DM.jpg",
"https://i.imgur.com/Qd9HTwd.png",
"https://i.imgur.com/ac6KKLa.png",
"https://i.imgur.com/zGJFv9i.png",
"https://i.imgur.com/sxg5Tla.png",
"https://i.imgur.com/9xVDLH0.png",
"https://i.imgur.com/ChwTXut.png",
"https://i.imgur.com/axhoTkz.jpg",
"https://i.imgur.com/DVwP1Hc.jpg",
"https://i.imgur.com/a54FLwA.jpg",
"https://i.imgur.com/TLpOWkL.jpg",
"https://i.imgur.com/KgyCKwG.jpg",
"https://i.imgur.com/iyYn5mZ.png",
"https://i.imgur.com/NywenGY.jpg",
"https://i.imgur.com/2SID7Pf.png",
"https://i.imgur.com/PLoluJp.png",
"https://i.imgur.com/Biulrcm.jpg",
"https://i.imgur.com/NSzyxVe.jpg",
"https://i.imgur.com/4qKojB8.jpg",
"https://i.imgur.com/mHEB06Z.jpg",
"https://i.imgur.com/OscSKs1.jpg",
"https://i.imgur.com/J72vzu1.jpg",
"https://i.imgur.com/1xKq9B5.jpg",
"https://i.imgur.com/21VxRRH.jpg",
"https://i.imgur.com/CeISQoZ.jpg",
"https://i.imgur.com/68lD2K7.png",
"https://i.imgur.com/26vpYDr.jpg",
"https://i.imgur.com/RWudoP4.png",
"https://i.imgur.com/BgSqVkG.png",
"https://i.imgur.com/6bXbnaf.jpg",
"https://i.imgur.com/jToF5Aq.jpg",
"https://i.imgur.com/Aj2fSm2.jpg",
"https://i.imgur.com/q9gxqRg.jpg",
"https://i.imgur.com/05aN7Xx.jpg",
"https://i.imgur.com/CnzBmVH.jpg",
"https://i.imgur.com/FfFqTBQ.jpg",
"https://i.imgur.com/3AWM626.jpg",
"https://i.imgur.com/giJJsqc.jpg",
"https://i.imgur.com/zZcKr2N.jpg",
"https://i.imgur.com/cvCFRRp.jpg",
"https://i.imgur.com/cpUMmby.jpg",
"https://i.imgur.com/uSWYMmw.jpg",
"https://i.imgur.com/9Cu2hqC.jpg",
"https://i.imgur.com/M3hYtSb.jpg",
"https://i.imgur.com/sc4fI80.jpg",
"https://i.imgur.com/Br2Ewes.jpg",
"https://i.imgur.com/oNXN9BB.jpg",
"https://i.imgur.com/fSfYlKp.jpg",
"https://i.imgur.com/iqnjB9K.jpg",
"https://i.imgur.com/wQyHZIB.jpg",
"https://i.imgur.com/6xIFwne.jpg",
"https://i.imgur.com/ncvwYbO.jpg",
"https://i.imgur.com/LKlExzN.jpg",
"https://i.imgur.com/Kp2pPQi.jpg",
"https://i.imgur.com/3KJYpyR.jpg",
"https://i.imgur.com/dy0bMAG.jpg",
"https://i.imgur.com/ZYuinzL.jpg",
"https://i.imgur.com/sXlapeX.jpg",
"https://i.imgur.com/3EjbKlr.jpg",
"https://i.imgur.com/E150e1H.jpg",
"https://i.imgur.com/HhKC0N2.jpg",
"https://i.imgur.com/YKX2DSk.jpg",
"https://i.imgur.com/LFBBdSg.jpg",
"https://i.imgur.com/JYeV7TG.jpg",
"https://i.imgur.com/fuHKVr0.jpg",
"https://i.imgur.com/ZFWKAGc.jpg",
"https://i.imgur.com/tv7wePd.jpg",
"https://i.imgur.com/hahfnWM.jpg",
"https://i.imgur.com/QhYc9t0.jpg",
"https://i.imgur.com/B7mzVYg.jpg",
"https://i.imgur.com/sMTu13n.jpg",
"https://i.imgur.com/41MxzFb.jpg",
"https://i.imgur.com/VTHMirB.jpg",
"https://i.imgur.com/ISiPTLH.jpg",
"https://i.imgur.com/oJzYKMu.jpg",
"https://i.imgur.com/Gz3LZFw.jpg",
"https://i.imgur.com/U9oB6CM.jpg",
"https://i.imgur.com/bQaJXpd.jpg",
"https://i.imgur.com/hooQuJg.jpg",
"https://i.imgur.com/Xur4Qsc.jpg",
"https://i.imgur.com/AjviC8i.jpg",
"https://i.imgur.com/QlfeWOo.jpg",
"https://i.imgur.com/LLU12B0.jpg",
"https://i.imgur.com/I8BSzcC.jpg",
"https://i.imgur.com/yV1Rl2l.jpg",
"https://i.imgur.com/MwuUbH1.jpg",
"https://i.imgur.com/ltH1Gn6.jpg",
"https://i.imgur.com/92WaRhR.jpg",
"https://i.imgur.com/AvHSLy7.jpg",
"https://i.imgur.com/g1qgQRG.jpg",
"https://i.imgur.com/VbjFJZE.jpg",
"https://i.imgur.com/ZbybJey.jpg",
"https://i.imgur.com/VwUZuow.jpg,",
"https://i.imgur.com/e1wKISs.jpg",
"https://i.imgur.com/gi2tFo7.jpg",
"https://i.imgur.com/JjgMwBU.jpg",
"https://i.imgur.com/5cvknfP.jpg",
"https://i.imgur.com/VueFFQ3.jpg",
"https://i.imgur.com/wbLjqni.jpg",
"https://i.imgur.com/qxmcr7u.jpg",
"https://i.imgur.com/7avYIYn.jpg",
"https://i.imgur.com/Iy5UAnm.jpg",
"https://i.imgur.com/UQ6b87s.jpg",
"https://i.imgur.com/34iejkq.jpg",
"https://i.imgur.com/qjch9uW.jpg",
"https://i.imgur.com/QSWz9Ip.jpg",
"https://i.imgur.com/7fzbYtC.jpg",
"https://i.imgur.com/HZfJNoS.jpg",
"https://i.imgur.com/cZqeIxc.jpg",
"https://i.imgur.com/mXuvyTo.jpg",
"https://i.imgur.com/8WRKC00.jpg",
"https://i.imgur.com/x7omaPh.jpg",
"https://i.imgur.com/kAI0m0v.jpg",
"https://i.imgur.com/fOgmjOR.jpg",
"https://i.imgur.com/Hx94LP0.jpg",
"https://i.imgur.com/1DaWWEn.jpg",
"https://i.imgur.com/9s0z7Gj.jpg",
"https://i.imgur.com/trmzLxv.jpg",
"https://i.imgur.com/1KSjgyc.jpg",
"https://i.imgur.com/Vk4oRrS.jpg",
"https://i.imgur.com/eOOKWVy.jpg",
"https://i.imgur.com/SyCdvtN.jpg",
"https://i.imgur.com/bAr5hWP.jpg",
"https://i.imgur.com/4HbdG1f.jpg",
"https://i.imgur.com/8yf3EIC.jpg",
"https://i.imgur.com/nAlBvO3.jpg",
"https://i.imgur.com/OdX2cAC.jpg",
"https://i.imgur.com/thFXKf2.jpg",
"https://i.imgur.com/BkMEGzS.jpg",
"https://i.imgur.com/x7jWKKB.jpg",
"https://i.imgur.com/thhXuVJ.jpg",
"https://i.imgur.com/matDT2H.jpg",
"https://i.imgur.com/LCjyYYm.jpg",
"https://i.imgur.com/RVoEXhK.jpg",
"https://i.imgur.com/qpMNtsX.jpg",
"https://i.imgur.com/VItKXMV.jpg",
"https://i.imgur.com/nCUdIqj.jpg",
"https://i.imgur.com/JLKpbaW.jpg",
"https://i.imgur.com/UoEulks.jpg",
"https://i.imgur.com/HkkKJE3.jpg",
"https://i.imgur.com/Y8zBbLD.jpg",
"https://i.imgur.com/HbD1LaM.jpg",
"https://i.imgur.com/dgmN11v.jpg",
"https://i.imgur.com/b54I07R.jpg",
"https://i.imgur.com/4w5JZik.jpg",
"https://i.imgur.com/0KOVXa7.jpg",
  ];
  var max = Math.floor(Math.random() * 6);  
var min = Math.floor(Math.random() * 2);
  var data = await Currencies.getData(event.senderID);
  var exp =  data.exp;
  var money = data.money
      if(money < 100) api.sendMessage("Bạn cần 100 đô để xem ảnh ?",event.threadID,event.messageID)
          else {
   Currencies.setData(event.senderID, options = {money: money - 100})
   var callback = () => api.sendMessage({body:`Ảnh Gura Nè\nSố Ảnh: ${link.length}\n-100 đô !`,attachment: fs.createReadStream(__dirname + "/cache/1.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/1.jpg"), event.messageID); 
      return request(encodeURI(link[Math.floor(Math.random() * link.length)] + (max - min))).pipe(fs.createWriteStream(__dirname+"/cache/1.jpg")).on("close",() => callback());
     }
   };
 
