module.exports.config = {
  name: "guujiyae",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Teri",
  description: "Random ảnh Guuji Yae",
  commandCategory: "genshin impact",
  usages: "guuji yae",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
    
};

module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
  var link = [
"https://i.imgur.com/cKEkrxL.jpeg",
"https://i.imgur.com/VaLw2pI.jpeg",
"https://i.imgur.com/xvBCw8i.jpeg",
"https://i.imgur.com/t12G7NV.jpeg",
"https://i.imgur.com/7SoR7Jb.jpeg",
"https://i.imgur.com/POvq8Zu.jpeg",
"https://i.imgur.com/XRLham7.jpeg",
"https://i.imgur.com/J2ukASp.jpeg",
"https://i.imgur.com/6crEwWU.jpeg",
"https://i.imgur.com/uI28urt.jpeg",
"https://i.imgur.com/hxoQVF3.jpeg",
"https://i.imgur.com/jjmLnqz.jpeg",
"https://i.imgur.com/q2nA95o.jpeg",
"https://i.imgur.com/7I9hEMm.jpeg",
"https://i.imgur.com/2rEJzdQ.jpeg",
"https://i.imgur.com/Hd3aZAq.jpeg",
"https://i.imgur.com/Tvkf2sv.jpeg",
"https://i.imgur.com/yZAoAtT.jpeg",
"https://i.imgur.com/4PTe4QZ.jpeg",
"https://i.imgur.com/Kqjm9il.jpeg",
"https://i.imgur.com/qvsMOHi.jpeg",
"https://i.imgur.com/muGNCzC.jpeg",
"https://i.imgur.com/lxhCWAL.jpeg",
"https://i.imgur.com/EwhuvhM.jpeg",
"https://i.imgur.com/XNv6ogx.jpeg",
"https://i.imgur.com/leMmP41.jpeg",
"https://i.imgur.com/dy0OSIx.jpeg",
"https://i.imgur.com/8EcxLCi.jpeg",
"https://i.imgur.com/Xx2cgni.jpeg",
"https://i.imgur.com/XORRTnk.jpeg",
"https://i.imgur.com/OkpdoWK.jpeg",
"https://i.imgur.com/KStkARg.jpeg",
"https://i.imgur.com/gLREaEs.jpeg",
"https://i.imgur.com/c2KHl0k.jpeg",
"https://i.imgur.com/RZy3T1o.jpeg",
"https://i.imgur.com/VO0grWF.jpeg",
"https://i.imgur.com/nXcwZ1p.jpeg",
"https://i.imgur.com/Ct3N3JO.jpeg",
"https://i.imgur.com/XDthqIh.jpeg",
"https://i.imgur.com/UX90PxQ.jpeg",
"https://i.imgur.com/zXOK3eI.jpeg",
"https://i.imgur.com/cJWvtfa.jpeg",
"https://i.imgur.com/Yhx0omj.jpeg",
"https://i.imgur.com/2BBFm5n.jpeg",
"https://i.imgur.com/jqrdkSH.jpeg",
"https://i.imgur.com/rqfbONq.jpeg",
"https://i.imgur.com/xTzPXjC.jpeg",
"https://i.imgur.com/yf4O7r6.jpeg",
"https://i.imgur.com/OLFnNvH.jpeg",
"https://i.imgur.com/SZkxlDV.jpeg",
"https://i.imgur.com/m2Y1qXO.jpeg",
"https://i.imgur.com/jHE0yF8.jpeg",
"https://i.imgur.com/KClVhuf.jpeg",
"https://i.imgur.com/pSvqXGf.jpeg",
"https://i.imgur.com/zGkv9ZW.jpeg",
"https://i.imgur.com/RDmigwP.jpeg",
"https://i.imgur.com/CxUwAo8.jpeg",
"https://i.imgur.com/JWU1d95.jpeg",
"https://i.imgur.com/nUvRKeC.jpeg",
"https://i.imgur.com/Dht8sJV.jpeg",
"https://i.imgur.com/xDTNtx1.jpeg",
"https://i.imgur.com/2UrWTMj.jpeg",
"https://i.imgur.com/tuFI9wl.jpeg",
"https://i.imgur.com/VsjngZ8.jpeg",
"https://i.imgur.com/ppZumeG.jpeg",
"https://i.imgur.com/8FS9I4O.jpeg",
"https://i.imgur.com/AnnLRQb.jpeg",
"https://i.imgur.com/wLZR3pe.jpeg",
"https://i.imgur.com/u0s4bdO.jpeg",
"https://i.imgur.com/zuGXmnh.jpeg",
"https://i.imgur.com/IPyhfDW.jpeg",
"https://i.imgur.com/vgHxjl9.jpeg",
"https://i.imgur.com/zZgKZxD.jpeg",
"https://i.imgur.com/HMi0t5s.jpeg",
"https://i.imgur.com/A7g7bPD.jpeg",
"https://i.imgur.com/nlf0UfW.jpeg",
"https://i.imgur.com/GMc2V1C.jpeg",
"https://i.imgur.com/IHMHlTc.jpeg",
"https://i.imgur.com/JdQE1R6.jpeg",
"https://i.imgur.com/fty8LIE.jpeg",
"https://i.imgur.com/OxINb0Z.jpeg",
"https://i.imgur.com/56IlkTM.jpeg",
"https://i.imgur.com/SEvbXEe.jpeg",
"https://i.imgur.com/JckRi60.jpeg",
"https://i.imgur.com/yqmw2Sk.jpeg",
"https://i.imgur.com/jCzZGVV.jpeg",
"https://i.imgur.com/Gi5k0Du.jpeg",
"https://i.imgur.com/ulg4WLR.jpeg",
"https://i.imgur.com/ZLVthsM.jpeg",
"https://i.imgur.com/EeHWEaD.jpeg",
"https://i.imgur.com/eHTxUTv.jpeg",
"https://i.imgur.com/wdxaZub.jpeg",
"https://i.imgur.com/GG4vpLS.jpeg",
"https://i.imgur.com/SlBuRgM.jpeg",
"https://i.imgur.com/SOgN7NI.jpeg",
"https://i.imgur.com/KpWnLjQ.jpeg",
"https://i.imgur.com/zpnZ9aG.jpeg",
"https://i.imgur.com/LH61J9P.jpeg",
"https://i.imgur.com/A6yVu4H.jpeg",
"https://i.imgur.com/XksAkOl.jpeg",
"https://i.imgur.com/t0GQ4DZ.jpeg",
"https://i.imgur.com/NIhrmJ1.jpeg",
"https://i.imgur.com/aQYYYPI.jpeg",
"https://i.imgur.com/d4vFn3d.jpeg",
"https://i.imgur.com/0i9QJ65.jpeg",
"https://i.imgur.com/n6byIce.jpeg",
"https://i.imgur.com/piVTG05.jpeg",
"https://i.imgur.com/zPXwh37.jpeg",
"https://i.imgur.com/0ErNmnC.jpeg",
"https://i.imgur.com/wZg6Irh.jpeg",
"https://i.imgur.com/SwLiiSn.jpeg",
"https://i.imgur.com/c38y82X.jpeg",
"https://i.imgur.com/1kHz5vp.jpeg",
"https://i.imgur.com/MmQbL6W.jpeg",
"https://i.imgur.com/TkUJ6K5.jpeg",
"https://i.imgur.com/v2UsRMk.jpeg",
"https://i.imgur.com/c7DPZd1.jpeg",
"https://i.imgur.com/fo1CpA7.jpeg",
"https://i.imgur.com/qf99vrm.jpeg",
"https://i.imgur.com/Vz9BPwT.jpeg",
"https://i.imgur.com/2griAH7.jpeg",
"https://i.imgur.com/b143Teg.jpeg",
"https://i.imgur.com/9SkLXy3.jpeg",
"https://i.imgur.com/zT0aBrM.jpeg",
"https://i.imgur.com/30ZcdVW.jpeg",
"https://i.imgur.com/erUJ1kE.jpeg",
"https://i.imgur.com/He3YnaG.jpeg",
"https://i.imgur.com/DcH0a3Y.jpeg",
"https://i.imgur.com/QpfNs4a.jpeg",
"https://i.imgur.com/OiZF7ar.jpeg",
"https://i.imgur.com/BAJDBLC.jpeg",
"https://i.imgur.com/zJ75F2z.jpeg",
"https://i.imgur.com/h8GMFPi.jpeg",
"https://i.imgur.com/5K4hgu7.jpeg",
"https://i.imgur.com/rTpSa9X.jpeg",
"https://i.imgur.com/q36Gd7x.jpeg",
"https://i.imgur.com/BVSoWIb.jpeg",
"https://i.imgur.com/3eKUVk6.jpeg",
"https://i.imgur.com/6K4gIoN.jpeg",
"https://i.imgur.com/QyDwSwp.jpeg",
"https://i.imgur.com/DGItLNt.jpeg",
"https://i.imgur.com/TMbPh3M.jpeg",
"https://i.imgur.com/ToGcO6d.jpeg",
"https://i.imgur.com/gNVziU2.jpeg",
"https://i.imgur.com/lELgJb2.jpeg",
"https://i.imgur.com/DIQOdEV.jpeg",
"https://i.imgur.com/OHKBSIB.jpeg",
"https://i.imgur.com/CrbEolY.jpeg",
"https://i.imgur.com/6Kb5hTM.jpeg",
"https://i.imgur.com/4HX36Dw.jpeg",
"https://i.imgur.com/RHwI09m.jpeg",
"https://i.imgur.com/fIAtweO.jpeg",
"https://i.imgur.com/akXg8Wp.jpeg",
"https://i.imgur.com/p1Tn0qS.jpeg",
"https://i.imgur.com/RaS7YdJ.jpeg",
"https://i.imgur.com/VkkMSG5.jpeg",
"https://i.imgur.com/w0dHgSL.jpeg",
"https://i.imgur.com/u4GDgog.jpeg",
"https://i.imgur.com/CFYBGLf.jpeg",
"https://i.imgur.com/KcHdCGi.jpeg",
"https://i.imgur.com/zUvKrhw.jpeg",
"https://i.imgur.com/nRA7uol.jpeg",
"https://i.imgur.com/QocJJ6h.jpeg",
"https://i.imgur.com/GtBCLZK.jpeg",
"https://i.imgur.com/YWU8f3s.jpeg",
"https://i.imgur.com/09iCPn3.jpeg",
"https://i.imgur.com/nrxflyT.jpeg",
"https://i.imgur.com/iP5CxgD.jpeg",
"https://i.imgur.com/LG3GRkW.jpeg",
"https://i.imgur.com/sAtoZd4.jpeg",
"https://i.imgur.com/UlMQtoS.jpeg",
"https://i.imgur.com/q7ObXpt.jpeg",
"https://i.imgur.com/zItTdDe.jpeg",
"https://i.imgur.com/pRx4bWf.jpeg",
"https://i.imgur.com/fntf1yC.jpeg",
"https://i.imgur.com/xVymCvz.jpeg",
"https://i.imgur.com/Lr0iweE.jpeg",
"https://i.imgur.com/9l6H4mS.jpeg",
"https://i.imgur.com/t0HqVS3.jpeg",
"https://i.imgur.com/yKw31iE.jpeg",
"https://i.imgur.com/JHeVikg.jpeg",
"https://i.imgur.com/ss26y53.jpeg",
"https://i.imgur.com/AWCr38A.jpeg",
"https://i.imgur.com/g6ZM7yK.jpeg",
"https://i.imgur.com/Ee1Dvni.jpeg",
"https://i.imgur.com/QX3jvjq.jpeg",
"https://i.imgur.com/EuIxKBk.jpeg",
"https://i.imgur.com/DLNc8Q7.jpeg",
"https://i.imgur.com/t9YNzA4.jpeg",
"https://i.imgur.com/hQaZZUB.jpeg",
"https://i.imgur.com/V1IqH4D.jpeg",
"https://i.imgur.com/RUQKb3U.jpeg",
"https://i.imgur.com/l7cPNW8.jpeg",
"https://i.imgur.com/QDVkE4S.jpeg",
"https://i.imgur.com/P4TPB9l.jpeg",
"https://i.imgur.com/2XtttCc.jpeg",
"https://i.imgur.com/pMtYELy.jpeg",
"https://i.imgur.com/KUglA7I.jpeg",
"https://i.imgur.com/3LOAgDn.jpeg",
"https://i.imgur.com/a0Lkg1F.jpeg",
"https://i.imgur.com/ezjHje4.jpeg",
"https://i.imgur.com/TbZ9p8x.jpeg",
"https://i.imgur.com/MT0lV9N.jpeg",
"https://i.imgur.com/gjYSUfX.jpeg",
"https://i.imgur.com/HwHVLJy.jpeg",
"https://i.imgur.com/hUiwcl2.jpeg",
"https://i.imgur.com/hlGVHXv.jpeg",
"https://i.imgur.com/dD859Nc.jpeg",
"https://i.imgur.com/PlQnoOD.jpeg",
"https://i.imgur.com/2JdF4Kh.jpeg",
"https://i.imgur.com/ActiRmT.jpeg",
"https://i.imgur.com/NqmlmZm.jpeg",
"https://i.imgur.com/FQN4teD.jpeg",
"https://i.imgur.com/XR3oxcX.jpeg",
"https://i.imgur.com/WIrV4vR.jpeg",
"https://i.imgur.com/Fh2DzWh.jpeg",
"https://i.imgur.com/V5TvZoV.jpeg",
"https://i.imgur.com/I8lv0zG.jpeg",
"https://i.imgur.com/41Bp852.jpeg",
"https://i.imgur.com/lr8GxxZ.jpeg",
"https://i.imgur.com/1tKuVTD.jpeg",
"https://i.imgur.com/VkSCvkB.jpeg",
"https://i.imgur.com/foHD0kx.jpeg",
"https://i.imgur.com/AScdjig.jpeg",
"https://i.imgur.com/ckkfTax.jpeg",
"https://i.imgur.com/xJeQBHd.jpeg",
"https://i.imgur.com/Kib48HZ.jpeg",
"https://i.imgur.com/Om5EmnJ.jpeg",
  ];
  var max = Math.floor(Math.random() * 6);  
var min = Math.floor(Math.random() * 2);
  var data = await Currencies.getData(event.senderID);
  var exp =  data.exp;
  var money = data.money
      if(money < 100) api.sendMessage("Bạn cần 100 đô để xem ảnh ?",event.threadID,event.messageID)
          else {
   Currencies.setData(event.senderID, options = {money: money - 100})
   var callback = () => api.sendMessage({body:`Guuji Yae\nSố Ảnh: ${link.length}\n-100 đô !`,attachment: fs.createReadStream(__dirname + "/cache/1.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/1.jpg"), event.messageID); 
      return request(encodeURI(link[Math.floor(Math.random() * link.length)] + (max - min))).pipe(fs.createWriteStream(__dirname+"/cache/1.jpg")).on("close",() => callback());
     }
   };
 
