module.exports.config = {
  name: "kokomi",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Teri",
  description: "Random ảnh Sanngonomiya kokomi",
  commandCategory: "genshin impact",
  usages: "kokomi",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
};

module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
  var link = [
           "https://i.imgur.com/Vjpaeay.jpeg",
           "https://i.imgur.com/K6wKojf.jpeg",
           "https://i.imgur.com/OcYbQaK.jpeg",
           "https://i.imgur.com/Okqqa0m.jpeg",
           "https://i.imgur.com/6ekfjCt.jpeg",
           "https://i.imgur.com/zCKsYYF.jpeg",
           "https://i.imgur.com/gtXQAAn.jpeg",
           "https://i.imgur.com/5hCuVUR.jpeg",
           "https://i.imgur.com/fN8lUlw.jpeg",
           "https://i.imgur.com/xN32k1b.jpeg",
           "https://i.imgur.com/CIxbq38.jpeg",
           "https://i.imgur.com/mUBrv8y.jpeg",
           "https://i.imgur.com/RsvzY3K.jpeg",
           "https://i.imgur.com/6h0NnfM.jpeg",
           "https://i.imgur.com/nM6ikCo.jpeg",
           "https://i.imgur.com/mk4jHXC.jpeg",
           "https://i.imgur.com/XI2Y6f9.jpeg",
           "https://i.imgur.com/CaYcEHF.jpeg",
           "https://i.imgur.com/IgWXJbr.jpeg",
           "https://i.imgur.com/X16yTkG.jpeg",
           "https://i.imgur.com/AVRQKmj.jpeg",
           "https://i.imgur.com/OPkHzem.jpeg",
           "https://i.imgur.com/sTqdvGY.jpeg",
           "https://i.imgur.com/XvCRzHW.jpeg",
           "https://i.imgur.com/iv5aVzM.jpeg",
           "https://i.imgur.com/VdxjtwO.jpeg",
           "https://i.imgur.com/BwnAJYN.jpeg",
           "https://i.imgur.com/KTvgLgo.jpeg",
           "https://i.imgur.com/UC3cwAM.jpeg",
           "https://i.imgur.com/rQto1sA.jpeg",
           "https://i.imgur.com/crDKkI9.jpeg",
           "https://i.imgur.com/HomrHyI.jpeg",
           "https://i.imgur.com/0tUMM9W.jpeg",
           "https://i.imgur.com/YNxAbYh.jpeg",
           "https://i.imgur.com/1O1Kkh4.jpeg",
           "https://i.imgur.com/w9jHMXS.jpeg",
           "https://i.imgur.com/dB5Fz7f.jpeg",
           "https://i.imgur.com/xKcL1A8.jpeg",
           "https://i.imgur.com/JTaKY4O.jpeg",
           "https://i.imgur.com/w79mf4z.jpeg",
           "https://i.imgur.com/iHwFxcb.jpeg",
           "https://i.imgur.com/hrhWUD0.jpeg",
           "https://i.imgur.com/JGPV26B.jpeg",
           "https://i.imgur.com/BrPmbSr.jpeg",
           "https://i.imgur.com/ldfPFVt.jpeg",
           "https://i.imgur.com/8Yp3pdR.jpeg",
           "https://i.imgur.com/p9hZsA2.jpeg",  
           "https://i.imgur.com/JOkR0Lf.jpeg",
           "https://i.imgur.com/XQcEQhK.jpeg",
           "https://i.imgur.com/R6FMfku.jpeg",
           "https://i.imgur.com/i43ZdJh.jpeg",
           "https://i.imgur.com/MgiwcH7.jpeg",
           "https://i.imgur.com/ymv1orL.jpeg",
           "https://i.imgur.com/5sqZwWe.jpeg",
           "https://i.imgur.com/z9K6IqF.jpeg",  
           "https://i.imgur.com/z9K6IqF.jpeg",
           "https://i.imgur.com/z9K6IqF.jpeg",
           "https://i.imgur.com/MIhMV4C.jpeg",
           "https://i.imgur.com/KawKi4j.jpeg",
           "https://i.imgur.com/Rb2PugG.jpeg",
           "https://i.imgur.com/9RTfSLo.jpeg",
           "https://i.imgur.com/qkEPVkH.jpeg",  
           "https://i.imgur.com/KawKi4j.jpeg",
           "https://i.imgur.com/MIhMV4C.jpeg",
           "https://i.imgur.com/81k1ikQ.jpeg",
           "https://i.imgur.com/eDLpvQs.jpeg",
           "https://i.imgur.com/QU61rS2.jpeg",
           "https://i.imgur.com/NBPOKfO.jpeg",
           "https://i.imgur.com/OhwH3FS.jpeg",
           "https://i.imgur.com/LNwoa1y.jpeg",  
           "https://i.imgur.com/BLXDbft.jpeg",
           "https://i.imgur.com/b1ieap2.jpeg",
           "https://i.imgur.com/iQODGH4.jpeg",
           "https://i.imgur.com/RRMAvpI.jpeg",
           "https://i.imgur.com/s5gn36J.jpeg",
           "https://i.imgur.com/ICl2Zki.jpeg",
           "https://i.imgur.com/SvJSrXQ.jpeg",  
           "https://i.imgur.com/A66nI9R.jpeg", 
           "https://i.imgur.com/5Vum5YR.jpeg",
           "https://i.imgur.com/JttuhZJ.jpeg",
           "https://i.imgur.com/96PkkBo.jpeg",
           "https://i.imgur.com/zMy04tx.jpeg",
           "https://i.imgur.com/akEHbjC.jpeg",  
           "https://i.imgur.com/jfujXQW.jpeg",
           "https://i.imgur.com/H9YbM1P.jpeg",
           "https://i.imgur.com/DFy1XCs.jpeg",
           "https://i.imgur.com/8QkYlPD.jpeg",
           "https://i.imgur.com/fmgDeqA.jpeg",
           "https://i.imgur.com/ObR8obb.jpeg",
           "https://i.imgur.com/M3ReeLC.jpeg",  
           "https://i.imgur.com/ZWXmIrB.jpeg",
           "https://i.imgur.com/p42nMGu.jpeg",
           "https://i.imgur.com/0cBhZSj.jpeg",
           "https://i.imgur.com/EzoapcI.jpeg",
           "https://i.imgur.com/GN95oWE.jpeg",  
                      "https://i.imgur.com/AwaR48B.jpeg",
           "https://i.imgur.com/CfxkX8q.jpeg",
           "https://i.imgur.com/yONeoJ6.jpeg",
           "https://i.imgur.com/PLPiTAu.jpeg",
           "https://i.imgur.com/b7GaG0l.jpeg",
           "https://i.imgur.com/hD52h6F.jpeg",
           "https://i.imgur.com/s21PwLD.jpeg",
           "https://i.imgur.com/DOjQlqw.jpeg",
           "https://i.imgur.com/udpqYAV.jpeg",
           "https://i.imgur.com/93AmzcX.jpeg",
           "https://i.imgur.com/6guHLiD.jpeg",
           "https://i.imgur.com/oHvJWh7.jpeg",
           "https://i.imgur.com/O00rVba.jpeg",
           "https://i.imgur.com/pMotjjU.jpeg",
           "https://i.imgur.com/XaH2SO2.jpeg",
           "https://i.imgur.com/iM4H056.jpeg",
           "https://i.imgur.com/VHHCY1F.jpeg",
           "https://i.imgur.com/eaTptqc.jpeg",
           "https://i.imgur.com/f7NEGfg.jpeg",
           "https://i.imgur.com/IksRtKv.jpeg",
           "https://i.imgur.com/o8jHXi1.jpeg",
           "https://i.imgur.com/NWkjS6F.jpeg",
           "https://i.imgur.com/wuXXTBn.jpeg",
           "https://i.imgur.com/yEVrKCj.jpeg",
           "https://i.imgur.com/PiRARZz.jpeg",
           "https://i.imgur.com/MvW2PRq.jpeg",
           "https://i.imgur.com/779fE9o.jpeg",
           "https://i.imgur.com/PnAQdIB.jpeg",
           "https://i.imgur.com/9BY1o9C.jpeg",
          "https://i.imgur.com/h3fa91P.jpg",
"https://i.imgur.com/Z1Ctp6a.jpg",
"https://i.imgur.com/sWKt2JH.jpg",
"https://i.imgur.com/SzzK7AV.jpeg",
"https://i.imgur.com/Ay5zfWm.jpeg",
"https://i.imgur.com/f48ddSE.jpeg",
"https://i.imgur.com/bbFbEUg.jpeg",
"https://i.imgur.com/Z9ZWdvw.jpeg",
"https://i.imgur.com/Xbnu04d.jpeg",
"https://i.imgur.com/YMTYsBU.jpeg",
"https://i.imgur.com/IYXeTTj.jpeg",
"https://i.imgur.com/87PFikc.jpeg",
"https://i.imgur.com/6YpiIFz.jpeg",
"https://i.imgur.com/3pk5GH7.jpeg",
"https://i.imgur.com/g96cBF6.jpeg",
"https://i.imgur.com/NDdTXpI.jpeg",
"https://i.imgur.com/1xjOFWs.jpeg",
"https://i.imgur.com/G8Ah7h6.jpeg",
"https://i.imgur.com/10izvlN.jpeg",
"https://i.imgur.com/HZ5iDgV.jpeg",
"https://i.imgur.com/S9vr0VZ.jpeg",
"https://i.imgur.com/7eNd2VD.jpeg",
"https://i.imgur.com/NN5ih57.jpeg",
"https://i.imgur.com/NSD0In9.jpeg",
"https://i.imgur.com/owa8syh.jpeg",
"https://i.imgur.com/BlbP2vQ.jpeg",
"https://i.imgur.com/l1lPHIn.jpeg",
"https://i.imgur.com/zkPMxc2.jpeg",
"https://i.imgur.com/bwqhoI9.jpeg",
"https://i.imgur.com/4Id15S5.jpeg",
"https://i.imgur.com/oSfXSXR.jpeg",
  ];
  var max = Math.floor(Math.random() * 6);  
var min = Math.floor(Math.random() * 2);
  var data = await Currencies.getData(event.senderID);
  var exp =  data.exp;
  var money = data.money
      if(money < 100) api.sendMessage("Bạn cần 100 đô để xem ảnh ?",event.threadID,event.messageID)
          else {
   Currencies.setData(event.senderID, options = {money: money - 100})
   var callback = () => api.sendMessage({body:` Sanngonomiya kokomi\nSố Ảnh: ${link.length}\n-100 đô !`,attachment: fs.createReadStream(__dirname + "/cache/1.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/1.jpg"), event.messageID); 
      return request(encodeURI(link[Math.floor(Math.random() * link.length)] + (max - min))).pipe(fs.createWriteStream(__dirname+"/cache/1.jpg")).on("close",() => callback());
     }
   };
