module.exports.config = {
  name: "miku",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Teri",
  description: "Random ảnh miku",
  commandCategory: "hình ảnh",
  usages: "miku",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
    
};

module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
  var link = [
"https://i.imgur.com/Fp61Z2p.jpeg",
"https://i.imgur.com/Mm9yYT1.jpeg",
"https://i.imgur.com/4EboIFR.jpeg",
"https://i.imgur.com/Ot5NRo9.jpeg",
"https://i.imgur.com/eAsufGG.jpeg",
"https://i.imgur.com/ImIQ7Yb.jpeg",
"https://i.imgur.com/SRzRZHA.jpeg",
"https://i.imgur.com/4q4X9Ft.jpeg",
"https://i.imgur.com/uwAULJ7.jpeg",
"https://i.imgur.com/3HEKj1u.jpeg",
"https://i.imgur.com/GZbySWw.jpeg",
"https://i.imgur.com/GBtYngt.jpeg",
"https://i.imgur.com/OUXCK14.jpeg",
"https://i.imgur.com/s1KtYdI.jpeg",
"https://i.imgur.com/55TBF01.jpeg",
"https://i.imgur.com/MW71eXV.jpeg",
"https://i.imgur.com/mHrf2Oi.jpeg",
"https://i.imgur.com/UJJwkMN.jpeg",
"https://i.imgur.com/vsOYAIY.jpeg",
"https://i.imgur.com/qssTTOq.jpeg",
"https://i.imgur.com/eyrurUu.jpeg",
"https://i.imgur.com/i8LrV6I.jpeg",
"https://i.imgur.com/Sy4pWoD.jpeg",
"https://i.imgur.com/Mnc7tpA.jpeg",
"https://i.imgur.com/viZ8l0Z.jpeg",
"https://i.imgur.com/EqhxPb6.jpeg",
"https://i.imgur.com/4Rm560e.jpeg",
"https://i.imgur.com/pYeqINo.jpeg",
"https://i.imgur.com/zi6SQhe.jpeg",
"https://i.imgur.com/xo2Qubz.jpeg",
"https://i.imgur.com/gSmHIxH.jpeg",
"https://i.imgur.com/ZCCJN2g.jpeg",
"https://i.imgur.com/fsHOmza.jpeg",
"https://i.imgur.com/OU3RQOR.jpeg",
"https://i.imgur.com/gqJsk9a.jpeg",
"https://i.imgur.com/CPYoIgE.jpeg",
"https://i.imgur.com/wAQu8PY.jpeg",
"https://i.imgur.com/ca9rdqi.jpeg",
"https://i.imgur.com/JuzAW9z.jpeg",
"https://i.imgur.com/yXKUdNf.jpeg",
"https://i.imgur.com/gacxaTV.jpeg",
"https://i.imgur.com/FNDkOFk.jpeg",
"https://i.imgur.com/fCGMFhk.jpeg",
"https://i.imgur.com/vZOJV0R.jpeg",
"https://i.imgur.com/gD4Bncx.jpeg",
"https://i.imgur.com/iaP6Mmh.jpeg",
"https://i.imgur.com/4t4hgMU.jpeg",
"https://i.imgur.com/EWGRJCx.jpeg",
"https://i.imgur.com/J4vr9Va.jpeg",
"https://i.imgur.com/7H2Mrru.jpeg",
"https://i.imgur.com/RpPkOUT.jpeg",
"https://i.imgur.com/YvUzZ0q.jpeg",
"https://i.imgur.com/qw48vPU.jpeg",
"https://i.imgur.com/VqQwp03.jpeg",
"https://i.imgur.com/CKVpeej.jpeg",
"https://i.imgur.com/93g4o7t.jpeg",
"https://i.imgur.com/tgQXL8d.jpeg",
"https://i.imgur.com/GFhovht.jpeg",
"https://i.imgur.com/qWjcBvf.jpeg",
"https://i.imgur.com/CDek3pL.jpeg",
"https://i.imgur.com/7RGltSd.jpeg",
"https://i.imgur.com/PiCPYux.jpeg",
"https://i.imgur.com/ZTw4Et7.jpeg",
"https://i.imgur.com/bhBN0S5.jpeg",
"https://i.imgur.com/6VskVxX.jpeg",
"https://i.imgur.com/ohkPiXV.jpeg",
"https://i.imgur.com/inVeFVi.jpeg",
"https://i.imgur.com/bXkgBGX.jpeg",
"https://i.imgur.com/6gHWYpP.jpeg",
"https://i.imgur.com/wLTP9rJ.jpeg",
"https://i.imgur.com/1hw4odQ.jpeg",
"https://i.imgur.com/n52OxGH.jpeg",
"https://i.imgur.com/3WTHbkh.jpeg",
"https://i.imgur.com/vhrHqh1.jpeg",
"https://i.imgur.com/qUJlBTS.jpeg",
"https://i.imgur.com/swD4WnN.jpeg",
"https://i.imgur.com/XqC4FT2.jpeg",
"https://i.imgur.com/fNQt6Qz.jpeg",
"https://i.imgur.com/2iubZId.jpeg",
"https://i.imgur.com/eFgE42P.jpeg",
"https://i.imgur.com/XRigYBs.jpeg",
"https://i.imgur.com/cTp4x05.jpeg",
"https://i.imgur.com/02VoWqF.jpeg",
"https://i.imgur.com/RCPCbCi.jpeg",
"https://i.imgur.com/B43WJ31.jpeg",
"https://i.imgur.com/UmVm7zd.jpeg",
"https://i.imgur.com/0vgGQcS.jpeg",
"https://i.imgur.com/xUXFrIc.jpeg",
"https://i.imgur.com/qVHVkEw.jpeg",
"https://i.imgur.com/D8LAhuu.jpeg",
"https://i.imgur.com/UOZHtBS.jpeg",
"https://i.imgur.com/tiTuh2l.jpeg",
"https://i.imgur.com/28yp1AN.jpeg",
"https://i.imgur.com/BqR4rwY.jpeg",
"https://i.imgur.com/vRjNu5t.jpeg",
"https://i.imgur.com/aei1sL8.jpeg",
"https://i.imgur.com/dkm4P2T.jpeg",
"https://i.imgur.com/4MvZf67.jpeg",
"https://i.imgur.com/XnH2J1q.jpeg",
"https://i.imgur.com/dHNVNYg.jpeg",
"https://i.imgur.com/gHrvOzz.jpeg",
"https://i.imgur.com/Ithr8FY.jpeg",
"https://i.imgur.com/svBqh3y.jpeg",
"https://i.imgur.com/iqm6ED8.jpeg",
"https://i.imgur.com/sJP2AQY.jpeg",
"https://i.imgur.com/hgNejth.jpeg",
"https://i.imgur.com/tpMsB24.jpeg",
"https://i.imgur.com/2P2ONvz.jpeg",
"https://i.imgur.com/2sPCRlY.jpeg",
"https://i.imgur.com/61q4Cq4.jpeg",
"https://i.imgur.com/oIPdzxJ.jpeg",
"https://i.imgur.com/eWtbuMj.jpeg",
"https://i.imgur.com/G8JNP68.jpeg",
"https://i.imgur.com/mNQzBMm.jpeg",
"https://i.imgur.com/lo8hUiX.jpeg",
"https://i.imgur.com/S2i3hRe.jpeg",
"https://i.imgur.com/pJ4ZoUb.jpeg",
"https://i.imgur.com/Q7yXFai.jpeg",
"https://i.imgur.com/u6F8bPf.jpeg",
"https://i.imgur.com/hR0Xg0b.jpeg",
"https://i.imgur.com/3cFSxSY.jpeg",
"https://i.imgur.com/464JDz7.jpeg",
"https://i.imgur.com/Zd4E1Ah.jpeg",
"https://i.imgur.com/c3Do9PB.jpeg",
"https://i.imgur.com/lqttEYg.jpeg",
"https://i.imgur.com/jHJ7VCt.jpeg",
"https://i.imgur.com/vq3W9HK.jpeg",
"https://i.imgur.com/eHH55ri.jpeg",
"https://i.imgur.com/2m1hyXn.jpeg",
"https://i.imgur.com/UbwgRrP.jpeg",
"https://i.imgur.com/tLtEkjf.jpeg",
"https://i.imgur.com/Qjy0aMO.jpeg",
"https://i.imgur.com/Mw0eUnb.jpeg",
"https://i.imgur.com/Htpk5Gs.jpeg",
"https://i.imgur.com/URe4YQa.jpeg",
"https://i.imgur.com/zadpLoS.jpeg",
"https://i.imgur.com/jLdCvHx.jpeg",
"https://i.imgur.com/G8jxK9Z.jpeg",
"https://i.imgur.com/ltW4Ki3.jpeg",
"https://i.imgur.com/5Gq0svT.jpeg",
"https://i.imgur.com/1uxItuB.jpeg",
"https://i.imgur.com/nw2Vi3u.jpeg",
"https://i.imgur.com/j7PAQLV.jpeg",
"https://i.imgur.com/pg855O6.jpeg",
"https://i.imgur.com/DGQzPeY.jpeg",
"https://i.imgur.com/o0GKNRE.jpeg",
"https://i.imgur.com/oswAcjD.jpeg",
"https://i.imgur.com/Sw2NAgk.jpeg",
"https://i.imgur.com/GlNrTS7.jpeg",
"https://i.imgur.com/ZbZI8Sv.jpeg",
"https://i.imgur.com/9U0IOtJ.jpeg",
"https://i.imgur.com/jd9W778.jpeg",
"https://i.imgur.com/0nkSCQY.jpeg",
"https://i.imgur.com/EWzfiyU.jpeg",
"https://i.imgur.com/hdXinzf.jpeg",
"https://i.imgur.com/iRhDYbt.jpeg",
"https://i.imgur.com/6XzCUrh.jpeg",
"https://i.imgur.com/DecMxMh.jpeg",
"https://i.imgur.com/2S0iSAs.jpeg",
"https://i.imgur.com/CcZ0apo.jpeg",
"https://i.imgur.com/knl7PX2.jpeg",
"https://i.imgur.com/9EZe7Y6.jpeg",
"https://i.imgur.com/KFw48dJ.jpeg",
"https://i.imgur.com/0pXK3oP.jpeg",
"https://i.imgur.com/tcP1f1h.jpeg",
"https://i.imgur.com/jwHJzEk.jpeg",
"https://i.imgur.com/a8SQanx.jpeg",
"https://i.imgur.com/3K9DWDO.jpeg",
"https://i.imgur.com/1cqbm5Z.jpeg",
"https://i.imgur.com/JFSAbiP.jpeg",
"https://i.imgur.com/F8y7y8o.jpeg",
"https://i.imgur.com/85jZyQs.jpeg",
"https://i.imgur.com/cVfAalG.jpeg",
"https://i.imgur.com/bpXynuM.jpeg",
"https://i.imgur.com/KUthrIX.jpeg",
"https://i.imgur.com/kUyZslF.jpeg",
"https://i.imgur.com/eHph2Gw.jpeg",
"https://i.imgur.com/6DVSPOy.jpeg",
"https://i.imgur.com/7sQpk9M.jpeg",
"https://i.imgur.com/XkJr94k.jpeg",
"https://i.imgur.com/tNjrrnt.jpeg",
"https://i.imgur.com/yG0SBee.jpeg",
"https://i.imgur.com/YyFWcOi.jpeg",
"https://i.imgur.com/yzd3fbH.jpeg",
"https://i.imgur.com/7X4A9FF.jpeg",
"https://i.imgur.com/eJOFsL0.jpeg",
"https://i.imgur.com/UC85TrV.jpeg",
"https://i.imgur.com/mponzsW.jpeg",
"https://i.imgur.com/hhCAZds.jpeg",
"https://i.imgur.com/mZoLICp.jpeg",
"https://i.imgur.com/d0rwtja.jpeg",
"https://i.imgur.com/89DgCHR.jpeg",
"https://i.imgur.com/rAteWrg.jpeg",
"https://i.imgur.com/ygrh0eD.jpeg",
"https://i.imgur.com/hpVveR0.jpeg",
"https://i.imgur.com/mCnjqoB.jpeg"
 ];
  var max = Math.floor(Math.random() * 6);  
var min = Math.floor(Math.random() * 2);
  var data = await Currencies.getData(event.senderID);
  var exp =  data.exp;
  var money = data.money
      if(money < 10) api.sendMessage("Bạn cần 10 đô để xem ảnh ?",event.threadID,event.messageID)
          else {
   Currencies.setData(event.senderID, options = {money: money - 10})
   var callback = () => api.sendMessage({body:`Ảnh miku Nè\nSố Ảnh: ${link.length}\n-10 đô !`,attachment: fs.createReadStream(__dirname + "/cache/1.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/1.jpg"), event.messageID); 
      return request(encodeURI(link[Math.floor(Math.random() * link.length)] + (max - min))).pipe(fs.createWriteStream(__dirname+"/cache/1.jpg")).on("close",() => callback());
     }
   };
 
