module.exports.config = {
  name: "sontung",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Teri",
  description: "Random ảnh sontung",
  commandCategory: "hình ảnh",
  usages: "sontung",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
    
};

module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
  var link = [
"https://i.imgur.com/ZOYT2m7.jpeg",
"https://i.imgur.com/xhacAiG.jpeg",
"https://i.imgur.com/FaF5lMv.jpeg",
"https://i.imgur.com/mrslhmS.jpeg",
"https://i.imgur.com/8BaI65A.jpeg",
"https://i.imgur.com/U9wjQH2.jpeg",
"https://i.imgur.com/mjwGTON.jpeg",
"https://i.imgur.com/23vvdrM.jpeg",
"https://i.imgur.com/VPuAL9S.jpeg",
"https://i.imgur.com/Dhwhqq9.jpeg",
"https://i.imgur.com/BjW6Bqk.jpeg",
"https://i.imgur.com/PmqdJip.jpeg",
"https://i.imgur.com/NKrp25j.jpeg",
"https://i.imgur.com/FCV5zEs.jpeg",
"https://i.imgur.com/09MQYzm.jpeg",
"https://i.imgur.com/smmxNfM.jpeg",
"https://i.imgur.com/yPI2s76.jpeg",
"https://i.imgur.com/3eJBUi8.jpeg",
"https://i.imgur.com/RmExTyL.jpeg",
"https://i.imgur.com/E5lUnS6.jpeg",
"https://i.imgur.com/TnluX2v.jpeg",
"https://i.imgur.com/HXr5mC1.jpeg",
"https://i.imgur.com/6M9EqR3.jpeg",
"https://i.imgur.com/9Lj7eMv.jpeg",
"https://i.imgur.com/FNbGlNb.jpeg",
"https://i.imgur.com/hUBbyBK.jpeg",
"https://i.imgur.com/ACmYx3t.jpeg",
"https://i.imgur.com/Rz5ajSb.jpeg",
"https://i.imgur.com/sD0xZN4.jpeg",
"https://i.imgur.com/8RRfyLv.jpeg",
"https://i.imgur.com/Isc1MBb.jpeg",
"https://i.imgur.com/EtxURnl.jpeg",
"https://i.imgur.com/MLwQSa0.jpeg",
"https://i.imgur.com/biS7T93.jpeg",
"https://i.imgur.com/YbX70Dd.jpeg",
"https://i.imgur.com/Rd4SRHA.jpeg",
"https://i.imgur.com/SbtBST7.jpeg",
"https://i.imgur.com/sTsPqHE.jpeg",
"https://i.imgur.com/8t6mKFn.jpeg",
"https://i.imgur.com/wsOLuB0.jpeg",
"https://i.imgur.com/Xww7mlS.jpeg",
"https://i.imgur.com/iaCYlDR.jpeg",
"https://i.imgur.com/4xOGAxj.jpeg",
"https://i.imgur.com/fOpn7lh.jpeg",
"https://i.imgur.com/LrU5bey.jpeg",
"https://i.imgur.com/PNRldUk.jpeg",
"https://i.imgur.com/iM486U6.jpeg",
"https://i.imgur.com/TFsEt51.jpeg",
"https://i.imgur.com/iPMZflb.jpeg",
"https://i.imgur.com/l25Z2yi.jpeg",
"https://i.imgur.com/S29csxe.jpeg",
"https://i.imgur.com/klwrue4.jpeg",
"https://i.imgur.com/E6ieOl2.jpeg",
"https://i.imgur.com/culE9Vv.jpeg",
"https://i.imgur.com/wPBwzty.jpeg",
"https://i.imgur.com/ApxnuJ7.jpeg",
"https://i.imgur.com/ZSglArM.jpeg",
"https://i.imgur.com/EcbGjfT.jpeg",
"https://i.imgur.com/Za3wZYx.jpeg",
"https://i.imgur.com/n3mUPxw.jpeg",
"https://i.imgur.com/3uBcwKM.jpeg",
"https://i.imgur.com/Ojq38jl.jpeg",
"https://i.imgur.com/yGeX6gP.jpeg",
"https://i.imgur.com/bE2ByGI.jpeg",
"https://i.imgur.com/SakyiLZ.jpeg",
"https://i.imgur.com/hV88mhr.jpeg",
"https://i.imgur.com/x99S1qZ.jpeg",
"https://i.imgur.com/xJnlywc.jpeg",
"https://i.imgur.com/xX9qr2I.jpeg",
"https://i.imgur.com/KPQtPOP.jpeg",
"https://i.imgur.com/vbfOYBN.jpeg",
"https://i.imgur.com/bY5xEqo.jpeg",
"https://i.imgur.com/olZtyBM.jpeg",
"https://i.imgur.com/0N7B0MN.jpeg",
"https://i.imgur.com/BtsryEL.jpeg",
"https://i.imgur.com/ZECk0V4.jpeg",
"https://i.imgur.com/6gQsV5m.jpeg",
"https://i.imgur.com/KmiRe7n.jpeg",
"https://i.imgur.com/jGFo4II.jpeg",
"https://i.imgur.com/iTmyOIt.jpeg",
"https://i.imgur.com/AwixlFm.jpeg",
"https://i.imgur.com/vUBleri.jpeg",
"https://i.imgur.com/60uuQJw.jpeg",
"https://i.imgur.com/bioP9gd.jpeg",
"https://i.imgur.com/AGUSzvB.jpeg",
"https://i.imgur.com/s65l4Vp.jpeg",
"https://i.imgur.com/sG0BnQq.jpeg",
"https://i.imgur.com/5ZhC9RD.jpeg",
"https://i.imgur.com/yve3Y06.jpeg",
"https://i.imgur.com/EQTZxuA.jpeg",
"https://i.imgur.com/1Mrmx6t.jpeg",
"https://i.imgur.com/CV9UYHg.jpeg",
"https://i.imgur.com/gvbT1wM.jpeg",
"https://i.imgur.com/vfn72dY.jpeg",
"https://i.imgur.com/j1CHgt2.jpeg",
"https://i.imgur.com/UbC5rxz.jpeg",
"https://i.imgur.com/qxo4BcN.jpeg",
"https://i.imgur.com/d6tvGz2.jpeg",
"https://i.imgur.com/f6ibdej.jpeg",
"https://i.imgur.com/lLuUkDi.jpeg",
"https://i.imgur.com/HgDL10f.jpeg",
"https://i.imgur.com/T4ugdXp.jpeg",
"https://i.imgur.com/pRPMoA6.jpeg",
"https://i.imgur.com/UlmB6gB.jpeg",
"https://i.imgur.com/DKEmMd6.jpeg",
"https://i.imgur.com/Y6aQr5C.jpeg",
"https://i.imgur.com/G6t3FMB.jpeg",
"https://i.imgur.com/3PFfz9D.jpeg",
"https://i.imgur.com/BXp7ygF.jpeg",
"https://i.imgur.com/IraKGvp.jpeg",
"https://i.imgur.com/qWr4Mcz.jpeg",
"https://i.imgur.com/cpUbJci.jpeg",
"https://i.imgur.com/5Xtu8vY.jpeg",
"https://i.imgur.com/u5znRL2.jpeg",
"https://i.imgur.com/HZl6oEG.jpeg",
"https://i.imgur.com/3O0LlRW.jpeg",
"https://i.imgur.com/mLPi9O2.jpeg",
"https://i.imgur.com/5bDAf0e.jpeg",
"https://i.imgur.com/N0Yrrag.jpeg",
"https://i.imgur.com/5EIoJoA.jpeg",
"https://i.imgur.com/38Xtncb.jpeg",
"https://i.imgur.com/mrHvUqd.jpeg",
"https://i.imgur.com/onJzB8D.jpeg",
"https://i.imgur.com/CqFFFhl.jpeg",
"https://i.imgur.com/RFLaeAg.jpeg",
"https://i.imgur.com/RyxAVPP.jpeg",
"https://i.imgur.com/AD7xeQk.jpeg",
"https://i.imgur.com/PtvbjYu.jpeg",
"https://i.imgur.com/iysNAox.jpeg",
"https://i.imgur.com/7bQE8Oq.jpeg",
"https://i.imgur.com/NijYy4x.jpeg",
"https://i.imgur.com/OHCrLU7.jpeg",
"https://i.imgur.com/VXjFYsP.jpeg",
"https://i.imgur.com/vRurc7t.jpeg",
"https://i.imgur.com/8FIJGrc.jpeg",
"https://i.imgur.com/w7tDgeo.jpeg",
"https://i.imgur.com/YdOLh82.jpeg",
"https://i.imgur.com/XPsaJmy.jpeg",
"https://i.imgur.com/FDJ1P06.jpeg",
"https://i.imgur.com/9az9EgB.jpeg",
"https://i.imgur.com/cipgrJy.jpeg",
"https://i.imgur.com/YCoiCeB.jpeg",
"https://i.imgur.com/dXNZdhZ.jpeg",
"https://i.imgur.com/64kqnlh.jpeg",
"https://i.imgur.com/sCKE4YF.jpeg",
"https://i.imgur.com/sCKE4YF.jpeg",
"https://i.imgur.com/ayiYliH.jpeg",
"https://i.imgur.com/ud4GoTq.jpeg",
"https://i.imgur.com/zrDcl2H.jpeg",
"https://i.imgur.com/nLcSOVt.jpeg",
"https://i.imgur.com/fmw9pLx.jpg",
"https://i.imgur.com/gNRMFdq.jpeg",
"https://i.imgur.com/8xJdvEN.jpeg",
"https://i.imgur.com/xn6zzrL.jpeg",
"https://i.imgur.com/ytBsmpg.jpeg",
"https://i.imgur.com/Ra3YPEZ.jpeg",
"https://i.imgur.com/c9MpCbV.jpeg",
"https://i.imgur.com/dpxdQpb.jpeg",
"https://i.imgur.com/0yCM7zu.jpeg",
"https://i.imgur.com/8vCMkEb.jpeg",
"https://i.imgur.com/W0psO04.jpeg",
"https://i.imgur.com/QBtqFcP.jpeg",
"https://i.imgur.com/SBHAtmI.jpeg",
"https://i.imgur.com/9u0L5XF.jpeg",
"https://i.imgur.com/fyrjR0H.jpeg",
"https://i.imgur.com/m0bbftE.jpeg",
"https://i.imgur.com/ywZF8xp.jpeg",
"https://i.imgur.com/qdqjmuM.jpeg",
"https://i.imgur.com/AZucXz8.jpeg",
"https://i.imgur.com/Q1CNM98.jpeg",
"https://i.imgur.com/BY2MaIL.jpeg",
"https://i.imgur.com/QTfYP4s.jpeg",
"https://i.imgur.com/0dH47Fc.jpeg",
"https://i.imgur.com/jl0xSgR.jpeg",
"https://i.imgur.com/74RPGB6.jpeg",
"https://i.imgur.com/011awLG.jpeg",
"https://i.imgur.com/C29canA.jpeg",
"https://i.imgur.com/2m1MwFB.jpeg",
"https://i.imgur.com/yO42oFz.jpeg",
"https://i.imgur.com/7qEzBmE.jpeg",
"https://i.imgur.com/x9GsUJz.jpeg",
"https://i.imgur.com/xu6ryKp.jpeg",
"https://i.imgur.com/88xbc7M.jpeg",
"https://i.imgur.com/QEq0zts.jpeg",
"https://i.imgur.com/JEpReu8.jpeg",
"https://i.imgur.com/nPFnOh1.jpeg",
"https://i.imgur.com/x4efEvR.jpeg",
"https://i.imgur.com/YBx5CWH.jpeg",
"https://i.imgur.com/pekqgco.jpeg",
"https://i.imgur.com/ue9OFfK.jpeg",
"https://i.imgur.com/t8iAxLC.jpeg",
"https://i.imgur.com/oWhfHJ7.jpeg",
"https://i.imgur.com/kJvO9As.jpeg",
"https://i.imgur.com/S2oA01G.jpeg",
"https://i.imgur.com/Inupfpu.jpeg",
"https://i.imgur.com/TQoHFcF.jpeg",
"https://i.imgur.com/DmZIHG1.jpeg",
"https://i.imgur.com/IermT7Z.jpeg",
"https://i.imgur.com/NtRmWJ4.jpeg",
 ];
  var max = Math.floor(Math.random() * 6);  
var min = Math.floor(Math.random() * 2);
  var data = await Currencies.getData(event.senderID);
  var exp =  data.exp;
  var money = data.money
      if(money < 100) api.sendMessage("Bạn cần 10 đô để xem ảnh ?",event.threadID,event.messageID)
          else {
   Currencies.setData(event.senderID, options = {money: money - 10})
   var callback = () => api.sendMessage({body:`Anh em sky ơi\nSố Ảnh: ${link.length}\n-10 đô !`,attachment: fs.createReadStream(__dirname + "/cache/1.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/1.jpg"), event.messageID); 
      return request(encodeURI(link[Math.floor(Math.random() * link.length)] + (max - min))).pipe(fs.createWriteStream(__dirname+"/cache/1.jpg")).on("close",() => callback());
     }
   };
 
